### ISSUE TITLE
Cannot find any entity corresponding to "Channel ID"

### ISSUE THREAD

**Issue by Stuser334** [David256/rcdtool#1]
script not recognizing any channel id

**Comment by David256** [comment]
Is your Telegram account a member of that channel?

**Comment by David256** [comment]
Change "Channel ID" by the real channel ID.

For example:
```
python rcdtool.py -C config.ini -C 1012345678 -M 201945 -O file.mp4
```

The channel ID can be found as decribed here: https://github.com/David256/rcdtool#where-i-find-these-ids

**Comment by David256** [comment]
Update and test again, I've changed a few things.
